/**
 * Static fallback data — used when Prisma is unavailable (e.g. on Cloudflare Pages).
 * Mirrors the seed.ts data structure exactly so the app works identically with or without DB.
 *
 * Source: Public Bangladesh government information (bangladesh.gov.bd and official portals).
 */

// ─── Divisions ───
export const divisions = [
  { id: 'd1', code: '10', nameBn: 'বরিশাল', nameEn: 'Barishal', slug: 'barishal', description: 'South-central coastal division' },
  { id: 'd2', code: '20', nameBn: 'চট্টগ্রাম', nameEn: 'Chattogram', slug: 'chattogram', description: 'South-eastern division' },
  { id: 'd3', code: '30', nameBn: 'ঢাকা', nameEn: 'Dhaka', slug: 'dhaka', description: 'Central division — capital region' },
  { id: 'd4', code: '40', nameBn: 'খুলনা', nameEn: 'Khulna', slug: 'khulna', description: 'South-western division' },
  { id: 'd5', code: '45', nameBn: 'ময়মনসিংহ', nameEn: 'Mymensingh', slug: 'mymensingh', description: 'North-central division' },
  { id: 'd6', code: '50', nameBn: 'রাজশাহী', nameEn: 'Rajshahi', slug: 'rajshahi', description: 'North-western division' },
  { id: 'd7', code: '55', nameBn: 'রংপুর', nameEn: 'Rangpur', slug: 'rangpur', description: 'Northern division' },
  { id: 'd8', code: '60', nameBn: 'সিলেট', nameEn: 'Sylhet', slug: 'sylhet', description: 'North-eastern division' },
]

// ─── Districts (64) ───
export const districts = [
  // Barishal
  { id: 'ds1', code: 'DIST-001', divisionSlug: 'barishal', nameBn: 'বরিশাল', nameEn: 'Barishal', slug: 'barishal-d', areaSqKm: 2723, population: 2530139 },
  { id: 'ds2', code: 'DIST-002', divisionSlug: 'barishal', nameBn: 'বরগুনা', nameEn: 'Barguna', slug: 'barguna', areaSqKm: 1831, population: 907849 },
  { id: 'ds3', code: 'DIST-003', divisionSlug: 'barishal', nameBn: 'ভোলা', nameEn: 'Bhola', slug: 'bhola', areaSqKm: 3737, population: 1850063 },
  { id: 'ds4', code: 'DIST-004', divisionSlug: 'barishal', nameBn: 'ঝালকাঠি', nameEn: 'Jhalokati', slug: 'jhalokati', areaSqKm: 758, population: 770426 },
  { id: 'ds5', code: 'DIST-005', divisionSlug: 'barishal', nameBn: 'পটুয়াখালী', nameEn: 'Patuakhali', slug: 'patuakhali', areaSqKm: 3221, population: 1689052 },
  { id: 'ds6', code: 'DIST-006', divisionSlug: 'barishal', nameBn: 'পিরোজপুর', nameEn: 'Pirojpur', slug: 'pirojpur', areaSqKm: 1308, population: 1160660 },
  // Chattogram
  { id: 'ds7', code: 'DIST-007', divisionSlug: 'chattogram', nameBn: 'চট্টগ্রাম', nameEn: 'Chattogram', slug: 'chattogram-d', areaSqKm: 5283, population: 9126125 },
  { id: 'ds8', code: 'DIST-008', divisionSlug: 'chattogram', nameBn: 'কুমিল্লা', nameEn: 'Cumilla', slug: 'cumilla', areaSqKm: 3085, population: 6245591 },
  { id: 'ds9', code: 'DIST-009', divisionSlug: 'chattogram', nameBn: 'কক্সবাজার', nameEn: "Cox's Bazar", slug: 'coxs-bazar', areaSqKm: 2295, population: 2529639 },
  { id: 'ds10', code: 'DIST-010', divisionSlug: 'chattogram', nameBn: 'ফেনী', nameEn: 'Feni', slug: 'feni', areaSqKm: 990, population: 1568733 },
  { id: 'ds11', code: 'DIST-011', divisionSlug: 'chattogram', nameBn: 'ব্রাহ্মণবাড়িয়া', nameEn: 'Brahmanbaria', slug: 'brahmanbaria', areaSqKm: 1927, population: 3115168 },
  { id: 'ds12', code: 'DIST-012', divisionSlug: 'chattogram', nameBn: 'খাগড়াছড়ি', nameEn: 'Khagrachhari', slug: 'khagrachhari', areaSqKm: 2701, population: 723339 },
  { id: 'ds13', code: 'DIST-013', divisionSlug: 'chattogram', nameBn: 'লক্ষ্মীপুর', nameEn: 'Lakshmipur', slug: 'lakshmipur', areaSqKm: 1456, population: 1912119 },
  { id: 'ds14', code: 'DIST-014', divisionSlug: 'chattogram', nameBn: 'নোয়াখালী', nameEn: 'Noakhali', slug: 'noakhali', areaSqKm: 3601, population: 3395219 },
  { id: 'ds15', code: 'DIST-015', divisionSlug: 'chattogram', nameBn: 'রাঙ্গামাটি', nameEn: 'Rangamati', slug: 'rangamati', areaSqKm: 6116, population: 622424 },
  { id: 'ds16', code: 'DIST-016', divisionSlug: 'chattogram', nameBn: 'চাঁদপুর', nameEn: 'Chandpur', slug: 'chandpur', areaSqKm: 1704, population: 2537995 },
  // Dhaka
  { id: 'ds17', code: 'DIST-017', divisionSlug: 'dhaka', nameBn: 'ঢাকা', nameEn: 'Dhaka', slug: 'dhaka-d', areaSqKm: 1464, population: 14052880 },
  { id: 'ds18', code: 'DIST-018', divisionSlug: 'dhaka', nameBn: 'ফরিদপুর', nameEn: 'Faridpur', slug: 'faridpur', areaSqKm: 2073, population: 2136316 },
  { id: 'ds19', code: 'DIST-019', divisionSlug: 'dhaka', nameBn: 'গাজীপুর', nameEn: 'Gazipur', slug: 'gazipur', areaSqKm: 1742, population: 4586910 },
  { id: 'ds20', code: 'DIST-020', divisionSlug: 'dhaka', nameBn: 'গোপালগঞ্জ', nameEn: 'Gopalganj', slug: 'gopalganj', areaSqKm: 1490, population: 1287940 },
  { id: 'ds21', code: 'DIST-021', divisionSlug: 'dhaka', nameBn: 'কিশোরগঞ্জ', nameEn: 'Kishoreganj', slug: 'kishoreganj', areaSqKm: 2691, population: 3087817 },
  { id: 'ds22', code: 'DIST-022', divisionSlug: 'dhaka', nameBn: 'মাদারীপুর', nameEn: 'Madaripur', slug: 'madaripur', areaSqKm: 1145, population: 1263351 },
  { id: 'ds23', code: 'DIST-023', divisionSlug: 'dhaka', nameBn: 'মানিকগঞ্জ', nameEn: 'Manikganj', slug: 'manikganj', areaSqKm: 1379, population: 1535775 },
  { id: 'ds24', code: 'DIST-024', divisionSlug: 'dhaka', nameBn: 'মুন্সিগঞ্জ', nameEn: 'Munshiganj', slug: 'munshiganj', areaSqKm: 1053, population: 1551548 },
  { id: 'ds25', code: 'DIST-025', divisionSlug: 'dhaka', nameBn: 'নারায়ণগঞ্জ', nameEn: 'Narayanganj', slug: 'narayanganj', areaSqKm: 683, population: 3598323 },
  { id: 'ds26', code: 'DIST-026', divisionSlug: 'dhaka', nameBn: 'নরসিংদী', nameEn: 'Narsingdi', slug: 'narsingdi', areaSqKm: 1142, population: 2416130 },
  { id: 'ds27', code: 'DIST-027', divisionSlug: 'dhaka', nameBn: 'রাজবাড়ী', nameEn: 'Rajbari', slug: 'rajbari', areaSqKm: 1093, population: 1133178 },
  { id: 'ds28', code: 'DIST-028', divisionSlug: 'dhaka', nameBn: 'শরীয়তপুর', nameEn: 'Shariatpur', slug: 'shariatpur', areaSqKm: 1174, population: 1235774 },
  { id: 'ds29', code: 'DIST-029', divisionSlug: 'dhaka', nameBn: 'টাঙ্গাইল', nameEn: 'Tangail', slug: 'tangail', areaSqKm: 3349, population: 3842389 },
  // Khulna
  { id: 'ds30', code: 'DIST-030', divisionSlug: 'khulna', nameBn: 'খুলনা', nameEn: 'Khulna', slug: 'khulna-d', areaSqKm: 4394, population: 2593733 },
  { id: 'ds31', code: 'DIST-031', divisionSlug: 'khulna', nameBn: 'বাগেরহাট', nameEn: 'Bagerhat', slug: 'bagerhat', areaSqKm: 3959, population: 1624579 },
  { id: 'ds32', code: 'DIST-032', divisionSlug: 'khulna', nameBn: 'চুয়াডাঙ্গা', nameEn: 'Chuadanga', slug: 'chuadanga', areaSqKm: 1157, population: 1208793 },
  { id: 'ds33', code: 'DIST-033', divisionSlug: 'khulna', nameBn: 'যশোর', nameEn: 'Jashore', slug: 'jashore', areaSqKm: 2607, population: 3022481 },
  { id: 'ds34', code: 'DIST-034', divisionSlug: 'khulna', nameBn: 'ঝিনাইদহ', nameEn: 'Jhenaidah', slug: 'jhenaidah', areaSqKm: 1957, population: 1918300 },
  { id: 'ds35', code: 'DIST-035', divisionSlug: 'khulna', nameBn: 'কুষ্টিয়া', nameEn: 'Kushtia', slug: 'kushtia', areaSqKm: 1621, population: 2057457 },
  { id: 'ds36', code: 'DIST-036', divisionSlug: 'khulna', nameBn: 'মাগুরা', nameEn: 'Magura', slug: 'magura', areaSqKm: 1599, population: 1031851 },
  { id: 'ds37', code: 'DIST-037', divisionSlug: 'khulna', nameBn: 'মেহেরপুর', nameEn: 'Meherpur', slug: 'meherpur', areaSqKm: 716, population: 668749 },
  { id: 'ds38', code: 'DIST-038', divisionSlug: 'khulna', nameBn: 'নড়াইল', nameEn: 'Narail', slug: 'narail', areaSqKm: 990, population: 726153 },
  { id: 'ds39', code: 'DIST-039', divisionSlug: 'khulna', nameBn: 'সাতক্ষীরা', nameEn: 'Satkhira', slug: 'satkhira', areaSqKm: 3858, population: 2237859 },
  // Mymensingh
  { id: 'ds40', code: 'DIST-040', divisionSlug: 'mymensingh', nameBn: 'ময়মনসিংহ', nameEn: 'Mymensingh', slug: 'mymensingh-d', areaSqKm: 4363, population: 5638169 },
  { id: 'ds41', code: 'DIST-041', divisionSlug: 'mymensingh', nameBn: 'জামালপুর', nameEn: 'Jamalpur', slug: 'jamalpur', areaSqKm: 2032, population: 2432922 },
  { id: 'ds42', code: 'DIST-042', divisionSlug: 'mymensingh', nameBn: 'নেত্রকোণা', nameEn: 'Netrokona', slug: 'netrokona', areaSqKm: 2274, population: 2292518 },
  { id: 'ds43', code: 'DIST-043', divisionSlug: 'mymensingh', nameBn: 'শেরপুর', nameEn: 'Sherpur', slug: 'sherpur', areaSqKm: 1364, population: 1468800 },
  // Rajshahi
  { id: 'ds44', code: 'DIST-044', divisionSlug: 'rajshahi', nameBn: 'রাজশাহী', nameEn: 'Rajshahi', slug: 'rajshahi-d', areaSqKm: 2407, population: 3041861 },
  { id: 'ds45', code: 'DIST-045', divisionSlug: 'rajshahi', nameBn: 'নাটোর', nameEn: 'Natore', slug: 'natore', areaSqKm: 1896, population: 1694741 },
  { id: 'ds46', code: 'DIST-046', divisionSlug: 'rajshahi', nameBn: 'নওগাঁ', nameEn: 'Naogaon', slug: 'naogaon', areaSqKm: 3436, population: 2790427 },
  { id: 'ds47', code: 'DIST-047', divisionSlug: 'rajshahi', nameBn: 'নবাবগঞ্জ', nameEn: 'Nawabganj', slug: 'nawabganj', areaSqKm: 1581, population: 1751522 },
  { id: 'ds48', code: 'DIST-048', divisionSlug: 'rajshahi', nameBn: 'পাবনা', nameEn: 'Pabna', slug: 'pabna', areaSqKm: 2377, population: 2724944 },
  { id: 'ds49', code: 'DIST-049', divisionSlug: 'rajshahi', nameBn: 'সিরাজগঞ্জ', nameEn: 'Sirajganj', slug: 'sirajganj', areaSqKm: 2498, population: 3245428 },
  { id: 'ds50', code: 'DIST-050', divisionSlug: 'rajshahi', nameBn: 'বগুড়া', nameEn: 'Bogura', slug: 'bogura', areaSqKm: 2912, population: 4090424 },
  { id: 'ds51', code: 'DIST-051', divisionSlug: 'rajshahi', nameBn: 'চাঁপাইনবাবগঞ্জ', nameEn: 'Chapainawabganj', slug: 'chapainawabganj', areaSqKm: 1745, population: 1755648 },
  { id: 'ds52', code: 'DIST-052', divisionSlug: 'rajshahi', nameBn: 'জয়পুরহাট', nameEn: 'Joypurhat', slug: 'joypurhat', areaSqKm: 1012, population: 1023032 },
  // Rangpur
  { id: 'ds53', code: 'DIST-053', divisionSlug: 'rangpur', nameBn: 'রংপুর', nameEn: 'Rangpur', slug: 'rangpur-d', areaSqKm: 2373, population: 3066771 },
  { id: 'ds54', code: 'DIST-054', divisionSlug: 'rangpur', nameBn: 'দিনাজপুর', nameEn: 'Dinajpur', slug: 'dinajpur', areaSqKm: 3433, population: 3082303 },
  { id: 'ds55', code: 'DIST-055', divisionSlug: 'rangpur', nameBn: 'গাইবান্ধা', nameEn: 'Gaibandha', slug: 'gaibandha', areaSqKm: 2180, population: 2518941 },
  { id: 'ds56', code: 'DIST-056', divisionSlug: 'rangpur', nameBn: 'কুড়িগ্রাম', nameEn: 'Kurigram', slug: 'kurigram', areaSqKm: 2296, population: 2286392 },
  { id: 'ds57', code: 'DIST-057', divisionSlug: 'rangpur', nameBn: 'লালমনিরহাট', nameEn: 'Lalmonirhat', slug: 'lalmonirhat', areaSqKm: 1259, population: 1370530 },
  { id: 'ds58', code: 'DIST-058', divisionSlug: 'rangpur', nameBn: 'নীলফামারী', nameEn: 'Nilphamari', slug: 'nilphamari', areaSqKm: 1581, population: 1965229 },
  { id: 'ds59', code: 'DIST-059', divisionSlug: 'rangpur', nameBn: 'পঞ্চগড়', nameEn: 'Panchagarh', slug: 'panchagarh', areaSqKm: 1405, population: 1245878 },
  { id: 'ds60', code: 'DIST-060', divisionSlug: 'rangpur', nameBn: 'ঠাকুরগাঁও', nameEn: 'Thakurgaon', slug: 'thakurgaon', areaSqKm: 1558, population: 1500727 },
  // Sylhet
  { id: 'ds61', code: 'DIST-061', divisionSlug: 'sylhet', nameBn: 'সিলেট', nameEn: 'Sylhet', slug: 'sylhet-d', areaSqKm: 3490, population: 11125000 },
  { id: 'ds62', code: 'DIST-062', divisionSlug: 'sylhet', nameBn: 'মৌলভীবাজার', nameEn: 'Moulvibazar', slug: 'moulvibazar', areaSqKm: 2799, population: 2285414 },
  { id: 'ds63', code: 'DIST-063', divisionSlug: 'sylhet', nameBn: 'হবিগঞ্জ', nameEn: 'Habiganj', slug: 'habiganj', areaSqKm: 2604, population: 2512639 },
  { id: 'ds64', code: 'DIST-064', divisionSlug: 'sylhet', nameBn: 'সুনামগঞ্জ', nameEn: 'Sunamganj', slug: 'sunamganj', areaSqKm: 3670, population: 2693521 },
]

// Helper to merge district with its division
export function getDistrictsWithDivision() {
  return districts.map((d) => {
    const division = divisions.find((v) => v.slug === d.divisionSlug)!
    return { ...d, division }
  })
}

// ─── Ministries (39) ───
export const ministries = [
  { id: 'm1', code: 'MOPA', nameBn: 'জনপ্রশাসন মন্ত্রণালয়', nameEn: 'Ministry of Public Administration', slug: 'public-administration', officialUrl: 'https://mopa.gov.bd/' },
  { id: 'm2', code: 'MOF', nameBn: 'অর্থ মন্ত্রণালয়', nameEn: 'Ministry of Finance', slug: 'finance', officialUrl: 'https://mof.gov.bd/' },
  { id: 'm3', code: 'MOFA', nameBn: 'পররাষ্ট্র মন্ত্রণালয়', nameEn: 'Ministry of Foreign Affairs', slug: 'foreign-affairs', officialUrl: 'https://mofa.gov.bd/' },
  { id: 'm4', code: 'MOHA', nameBn: 'স্বরাষ্ট্র মন্ত্রণালয়', nameEn: 'Ministry of Home Affairs', slug: 'home-affairs', officialUrl: 'https://moha.gov.bd/' },
  { id: 'm5', code: 'MOE', nameBn: 'শিক্ষা মন্ত্রণালয়', nameEn: 'Ministry of Education', slug: 'education', officialUrl: 'https://moe.gov.bd/' },
  { id: 'm6', code: 'MOPME', nameBn: 'প্রাথমিক ও গণশিক্ষা মন্ত্রণালয়', nameEn: 'Ministry of Primary and Mass Education', slug: 'primary-mass-education', officialUrl: 'https://mopme.gov.bd/' },
  { id: 'm7', code: 'MOHFW', nameBn: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়', nameEn: 'Ministry of Health and Family Welfare', slug: 'health-family-welfare', officialUrl: 'https://mohfw.gov.bd/' },
  { id: 'm8', code: 'MOA', nameBn: 'কৃষি মন্ত্রণালয়', nameEn: 'Ministry of Agriculture', slug: 'agriculture', officialUrl: 'https://moa.gov.bd/' },
  { id: 'm9', code: 'MOL', nameBn: 'ভূমি মন্ত্রণালয়', nameEn: 'Ministry of Land', slug: 'land', officialUrl: 'https://minland.gov.bd/' },
  { id: 'm10', code: 'MOLJPA', nameBn: 'আইন, বিচার ও সংসদ বিষয়ক মন্ত্রণালয়', nameEn: 'Ministry of Law, Justice and Parliamentary Affairs', slug: 'law-justice', officialUrl: 'https://moljpa.gov.bd/' },
  { id: 'm11', code: 'MOSW', nameBn: 'সমাজকল্যাণ মন্ত্রণালয়', nameEn: 'Ministry of Social Welfare', slug: 'social-welfare', officialUrl: 'https://msw.gov.bd/' },
  { id: 'm12', code: 'MOWCA', nameBn: 'নারী ও শিশু বিষয়ক মন্ত্রণালয়', nameEn: 'Ministry of Women and Children Affairs', slug: 'women-children', officialUrl: 'https://mowca.gov.bd/' },
  { id: 'm13', code: 'MOPT', nameBn: 'ডাক, টেলিযোগাযোগ ও তথ্যপ্রযুক্তি মন্ত্রণালয়', nameEn: 'Ministry of Posts, Telecommunications and ICT', slug: 'posts-ict', officialUrl: 'https://moptit.gov.bd/' },
  { id: 'm14', code: 'MODMR', nameBn: 'দুর্যোগ ব্যবস্থাপনা ও ত্রাণ মন্ত্রণালয়', nameEn: 'Ministry of Disaster Management and Relief', slug: 'disaster-management', officialUrl: 'https://modmr.gov.bd/' },
  { id: 'm15', code: 'MOENV', nameBn: 'পরিবেশ, বন ও জলবায়ু পরিবর্তন মন্ত্রণালয়', nameEn: 'Ministry of Environment, Forest and Climate Change', slug: 'environment-forest', officialUrl: 'https://env.gov.bd/' },
  { id: 'm16', code: 'MOWR', nameBn: 'জলসম্পদ মন্ত্রণালয়', nameEn: 'Ministry of Water Resources', slug: 'water-resources', officialUrl: 'https://mowr.gov.bd/' },
  { id: 'm17', code: 'MOP', nameBn: 'পরিকল্পনা মন্ত্রণালয়', nameEn: 'Ministry of Planning', slug: 'planning', officialUrl: 'https://plandiv.gov.bd/' },
  { id: 'm18', code: 'MOPW', nameBn: 'গণপূর্ত মন্ত্রণালয়', nameEn: 'Ministry of Public Works', slug: 'public-works', officialUrl: 'https://pwd.gov.bd/' },
  { id: 'm19', code: 'MOC', nameBn: 'বাণিজ্য মন্ত্রণালয়', nameEn: 'Ministry of Commerce', slug: 'commerce', officialUrl: 'https://mincom.gov.bd/' },
  { id: 'm20', code: 'MOIND', nameBn: 'শিল্প মন্ত্রণালয়', nameEn: 'Ministry of Industries', slug: 'industries', officialUrl: 'https://moind.gov.bd/' },
  { id: 'm21', code: 'MOLGRD', nameBn: 'স্থানীয় সরকার, পল্লী উন্নয়ন ও সমবায় মন্ত্রণালয়', nameEn: 'Ministry of Local Government, Rural Development and Cooperatives', slug: 'local-government', officialUrl: 'https://lgd.gov.bd/' },
  { id: 'm22', code: 'MOR', nameBn: 'রেলপথ মন্ত্রণালয়', nameEn: 'Ministry of Railways', slug: 'railways', officialUrl: 'https://railway.gov.bd/' },
  { id: 'm23', code: 'MORTB', nameBn: 'সড়ক পরিবহন ও সেতু মন্ত্রণালয়', nameEn: 'Ministry of Road Transport and Bridges', slug: 'road-transport', officialUrl: 'https://rthd.gov.bd/' },
  { id: 'm24', code: 'MOSHIP', nameBn: 'নৌপরিবহন মন্ত্রণালয়', nameEn: 'Ministry of Shipping', slug: 'shipping', officialUrl: 'https://mos.gov.bd/' },
  { id: 'm25', code: 'MOCAT', nameBn: 'বেসামরিক বিমান চলাচল ও পর্যটন মন্ত্রণালয়', nameEn: 'Ministry of Civil Aviation and Tourism', slug: 'civil-aviation', officialUrl: 'https://modtk.gov.bd/' },
  { id: 'm26', code: 'MOYS', nameBn: 'যুব ও ক্রীড়া মন্ত্রণালয়', nameEn: 'Ministry of Youth and Sports', slug: 'youth-sports', officialUrl: 'https://moys.gov.bd/' },
  { id: 'm27', code: 'MOEWOE', nameBn: 'প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়', nameEn: 'Ministry of Expatriates Welfare and Overseas Employment', slug: 'expatriates-welfare', officialUrl: 'https://probashi.gov.bd/' },
  { id: 'm28', code: 'MOINFO', nameBn: 'তথ্য ও সম্প্রচার মন্ত্রণালয়', nameEn: 'Ministry of Information and Broadcasting', slug: 'information', officialUrl: 'https://moi.gov.bd/' },
  { id: 'm29', code: 'MOCULT', nameBn: 'সাংস্কৃতিক বিষয়ক মন্ত্রণালয়', nameEn: 'Ministry of Cultural Affairs', slug: 'cultural-affairs', officialUrl: 'https://moca.gov.bd/' },
  { id: 'm30', code: 'MOCHTA', nameBn: 'পার্বত্য চট্টগ্রাম বিষয়ক মন্ত্রণালয়', nameEn: 'Ministry of Chittagong Hill Tracts Affairs', slug: 'cht-affairs', officialUrl: 'https://mochta.gov.bd/' },
  { id: 'm31', code: 'MOPEMR', nameBn: 'বিদ্যুৎ, জ্বালানি ও খনিজ সম্পদ মন্ত্রণালয়', nameEn: 'Ministry of Power, Energy and Mineral Resources', slug: 'power-energy', officialUrl: 'https://powerdivision.gov.bd/' },
  { id: 'm32', code: 'MOTJ', nameBn: 'পাট ও বস্ত্র মন্ত্রণালয়', nameEn: 'Ministry of Textiles and Jute', slug: 'textiles-jute', officialUrl: 'https://motj.gov.bd/' },
  { id: 'm33', code: 'MOFOOD', nameBn: 'খাদ্য মন্ত্রণালয়', nameEn: 'Ministry of Food', slug: 'food', officialUrl: 'https://food.gov.bd/' },
  { id: 'm34', code: 'MOLE', nameBn: 'শ্রম ও কর্মসংস্থান মন্ত্রণালয়', nameEn: 'Ministry of Labour and Employment', slug: 'labour-employment', officialUrl: 'https://mole.gov.bd/' },
  { id: 'm35', code: 'MOFL', nameBn: 'মৎস্য ও প্রাণিসম্পদ মন্ত্রণালয়', nameEn: 'Ministry of Fisheries and Livestock', slug: 'fisheries-livestock', officialUrl: 'https://mofl.gov.bd/' },
  { id: 'm36', code: 'MORA', nameBn: 'ধর্ম বিষয়ক মন্ত্রণালয়', nameEn: 'Ministry of Religious Affairs', slug: 'religious-affairs', officialUrl: 'https://mora.gov.bd/' },
  { id: 'm37', code: 'MOST', nameBn: 'বিজ্ঞান ও প্রযুক্তি মন্ত্রণালয়', nameEn: 'Ministry of Science and Technology', slug: 'science-technology', officialUrl: 'https://most.gov.bd/' },
  { id: 'm38', code: 'MOHPW', nameBn: 'গৃহায়ণ ও গণপূর্ত মন্ত্রণালয়', nameEn: 'Ministry of Housing and Public Works', slug: 'housing-public-works', officialUrl: 'https://mohpw.gov.bd/' },
  { id: 'm39', code: 'MOD', nameBn: 'প্রতিরক্ষা মন্ত্রণালয়', nameEn: 'Ministry of Defence', slug: 'defence', officialUrl: 'https://mod.gov.bd/' },
]

// ─── Organizations (39) ───
export const organizations = [
  { id: 'o1', nameBn: 'পাসপোর্ট অধিদপ্তর', nameEn: 'Department of Immigration and Passports', slug: 'immigration-passports', organizationType: 'directorate', ministryCode: 'MOHA', officialUrl: 'https://www.passport.gov.bd/', phone: '+8802-555502608', email: 'info@passport.gov.bd', addressEn: 'E-7, Bhaban, 1, Kawran Bazar, Dhaka-1215', addressBn: 'ই-৭ ভবন, ১, কাওরান বাজার, ঢাকা-১২১৫' },
  { id: 'o2', nameBn: 'জন্ম ও মৃত্যু নিবন্ধন অধিদপ্তর', nameEn: 'Office of the Registrar General, Birth & Death Registration', slug: 'birth-death-registration', organizationType: 'directorate', ministryCode: 'MOLGRD', officialUrl: 'https://bdris.gov.bd/', addressEn: 'Agargaon, Dhaka', addressBn: 'আগারগাঁও, ঢাকা' },
  { id: 'o3', nameBn: 'জাতীয় পরিচয়পত্র নিবন্ধন অধিদপ্তর', nameEn: 'National Identity Registration Division', slug: 'nid-registration', organizationType: 'directorate', ministryCode: 'MOST', officialUrl: 'https://services.nidw.gov.bd/', addressEn: 'E-8, Bhaban, Segunbagicha, Dhaka', addressBn: 'ই-৮ ভবন, সেগুনবাগিচা, ঢাকা' },
  { id: 'o4', nameBn: 'ভূমি রেকর্ড অধিদপ্তর', nameEn: 'Directorate of Land Record and Survey', slug: 'land-records', organizationType: 'directorate', ministryCode: 'MOL', officialUrl: 'https://dlrs.gov.bd/', addressEn: '32, Topkhana Road, Dhaka', addressBn: '৩২, তোপখানা রোড, ঢাকা' },
  { id: 'o5', nameBn: 'বাংলাদেশ সড়ক পরিবহন কর্তৃপক্ষ', nameEn: 'Bangladesh Road Transport Authority (BRTA)', slug: 'brta', organizationType: 'authority', ministryCode: 'MORTB', officialUrl: 'https://brta.gov.bd/', phone: '+8802-550009911', addressEn: 'Old 9, New 13, Fulbaria, Dhaka-1000', addressBn: 'পুরাতন ৯, নতুন ১৩, ফুলবাড়িয়া, ঢাকা-১০০০' },
  { id: 'o6', nameBn: 'জাতীয় রাজস্ব বোর্ড', nameEn: 'National Board of Revenue (NBR)', slug: 'nbr', organizationType: 'board', ministryCode: 'MOF', officialUrl: 'https://nbr.gov.bd/', addressEn: 'Segunbagicha, Dhaka', addressBn: 'সেগুনবাগিচা, ঢাকা' },
  { id: 'o7', nameBn: 'বাংলাদেশ ব্যাংক', nameEn: 'Bangladesh Bank', slug: 'bangladesh-bank', organizationType: 'corporation', ministryCode: 'MOF', officialUrl: 'https://www.bangladesh-bank.org/', addressEn: 'Motijheel, Dhaka', addressBn: 'মতিঝিল, ঢাকা' },
  { id: 'o8', nameBn: 'বাংলাদেশ বিদ্যুৎ উন্নয়ন বোর্ড', nameEn: 'Bangladesh Power Development Board (BPDB)', slug: 'bpdb', organizationType: 'board', ministryCode: 'MOPEMR', officialUrl: 'https://www.bpdb.gov.bd/', addressEn: '1, WAPDA Bhaban, Motijheel, Dhaka', addressBn: '১, ওয়াপদা ভবন, মতিঝিল, ঢাকা' },
  { id: 'o9', nameBn: 'ঢাকা ইলেকট্রিক সাপ্লাই কোম্পানি', nameEn: 'Dhaka Electric Supply Company (DESCO)', slug: 'desco', organizationType: 'corporation', ministryCode: 'MOPEMR', officialUrl: 'https://www.desco.org.bd/', addressEn: '198, Kawran Bazar, Dhaka', addressBn: '১৯৮, কাওরান বাজার, ঢাকা' },
  { id: 'o10', nameBn: 'বাংলাদেশ টেলিকমিউনিকেশন কোম্পানি লিমিটেড', nameEn: 'Bangladesh Telecommunications Company Limited (BTCL)', slug: 'btcl', organizationType: 'corporation', ministryCode: 'MOPT', officialUrl: 'https://www.btcl.com.bd/', addressEn: '37, Kawran Bazar, Dhaka', addressBn: '৩৭, কাওরান বাজার, ঢাকা' },
  { id: 'o11', nameBn: 'বাংলাদেশ ডাক বিভাগ', nameEn: 'Bangladesh Post Office', slug: 'post-office', organizationType: 'directorate', ministryCode: 'MOPT', officialUrl: 'https://www.bangladeshpost.gov.bd/', addressEn: 'Motijheel, Dhaka', addressBn: 'মতিঝিল, ঢাকা' },
  { id: 'o12', nameBn: 'দুর্নীতি দমন কমিশন', nameEn: 'Anti-Corruption Commission', slug: 'acc', organizationType: 'commission', ministryCode: 'MOLJPA', officialUrl: 'https://acc.org.bd/', addressEn: '1, Karwan Bazar, Dhaka', addressBn: '১, কাওরান বাজার, ঢাকা' },
  { id: 'o13', nameBn: 'নির্বাচন কমিশন বাংলাদেশ', nameEn: 'Election Commission Bangladesh', slug: 'election-commission', organizationType: 'commission', ministryCode: 'MOLJPA', officialUrl: 'https://ec.org.bd/', addressEn: 'Election Commission Bhaban, Agargaon, Dhaka', addressBn: 'নির্বাচন কমিশন ভবন, আগারগাঁও, ঢাকা' },
  { id: 'o14', nameBn: 'বাংলাদেশ সড়ক পরিবহন কর্পোরেশন', nameEn: 'Bangladesh Road Transport Corporation (BRTC)', slug: 'brtc', organizationType: 'corporation', ministryCode: 'MORTB', officialUrl: 'https://brtc.gov.bd/', addressEn: '108, Kazi Nazrul Islam Avenue, Dhaka', addressBn: '১০৮, কাজী নজরুল ইসলাম এভিনিউ, ঢাকা' },
  { id: 'o15', nameBn: 'মাধ্যমিক ও উচ্চ শিক্ষা অধিদপ্তর', nameEn: 'Directorate of Secondary and Higher Education (DSHE)', slug: 'dshe', organizationType: 'directorate', ministryCode: 'MOE', officialUrl: 'https://dshe.gov.bd/' },
  { id: 'o16', nameBn: 'প্রাথমিক শিক্ষা অধিদপ্তর', nameEn: 'Directorate of Primary Education (DPE)', slug: 'dpe', organizationType: 'directorate', ministryCode: 'MOPME', officialUrl: 'https://dpe.gov.bd/' },
  { id: 'o17', nameBn: 'স্বাস্থ্য অধিদপ্তর', nameEn: 'Directorate General of Health Services (DGHS)', slug: 'dghs', organizationType: 'directorate', ministryCode: 'MOHFW', officialUrl: 'https://dghs.gov.bd/' },
  { id: 'o18', nameBn: 'কৃষি সম্প্রসারণ অধিদপ্তর', nameEn: 'Department of Agricultural Extension (DAE)', slug: 'dae', organizationType: 'directorate', ministryCode: 'MOA', officialUrl: 'https://dae.gov.bd/' },
  { id: 'o19', nameBn: 'পল্লী উন্নয়ন বোর্ড', nameEn: 'Bangladesh Rural Development Board (BRDB)', slug: 'brdb', organizationType: 'board', ministryCode: 'MOLGRD', officialUrl: 'https://brdb.gov.bd/' },
  { id: 'o20', nameBn: 'পল্লী বিদ্যুতায়ন বোর্ড', nameEn: 'Rural Electrification Board (REB)', slug: 'reb', organizationType: 'board', ministryCode: 'MOPEMR', officialUrl: 'https://reb.gov.bd/' },
  { id: 'o21', nameBn: 'স্থানীয় সরকার প্রকৌশল অধিদপ্তর', nameEn: 'Local Government Engineering Department (LGED)', slug: 'lged', organizationType: 'directorate', ministryCode: 'MOLGRD', officialUrl: 'https://lged.gov.bd/' },
  { id: 'o22', nameBn: 'জনস্বাস্থ্য প্রকৌশল অধিদপ্তর', nameEn: 'Department of Public Health Engineering (DPHE)', slug: 'dphe', organizationType: 'directorate', ministryCode: 'MOLGRD', officialUrl: 'https://dphe.gov.bd/' },
  { id: 'o23', nameBn: 'বাংলাদেশ পরিসংখ্যান ব্যুরো', nameEn: 'Bangladesh Bureau of Statistics (BBS)', slug: 'bbs', organizationType: 'bureau', ministryCode: 'MOP', officialUrl: 'https://bbs.gov.bd/' },
  { id: 'o24', nameBn: 'বাংলাদেশ বিজ্ঞান ও শিল্প গবেষণা কাউন্সিল', nameEn: 'Bangladesh Council of Scientific and Industrial Research (BCSIR)', slug: 'bcsir', organizationType: 'council', ministryCode: 'MOST', officialUrl: 'https://bcsir.gov.bd/' },
  { id: 'o25', nameBn: 'বাংলাদেশ কৃষি গবেষণা ইনস্টিটিউট', nameEn: 'Bangladesh Agricultural Research Institute (BARI)', slug: 'bari', organizationType: 'institute', ministryCode: 'MOA', officialUrl: 'https://bari.gov.bd/' },
  { id: 'o26', nameBn: 'বাংলাদেশ পানি উন্নয়ন বোর্ড', nameEn: 'Bangladesh Water Development Board (BWDB)', slug: 'bwdb', organizationType: 'board', ministryCode: 'MOWR', officialUrl: 'https://bwdb.gov.bd/' },
  { id: 'o27', nameBn: 'দুর্যোগ ব্যবস্থাপনা অধিদপ্তর', nameEn: 'Department of Disaster Management (DDM)', slug: 'ddm', organizationType: 'directorate', ministryCode: 'MODMR', officialUrl: 'https://ddm.gov.bd/' },
  { id: 'o28', nameBn: 'পরিবেশ অধিদপ্তর', nameEn: 'Department of Environment (DoE)', slug: 'doe', organizationType: 'directorate', ministryCode: 'MOENV', officialUrl: 'https://doe.gov.bd/' },
  { id: 'o29', nameBn: 'বন অধিদপ্তর', nameEn: 'Forest Department', slug: 'forest-dept', organizationType: 'directorate', ministryCode: 'MOENV', officialUrl: 'https://forest.gov.bd/' },
  { id: 'o30', nameBn: 'তথ্য অধিদপ্তর', nameEn: 'Department of Information', slug: 'do-info', organizationType: 'directorate', ministryCode: 'MOINFO', officialUrl: 'https://doinfo.gov.bd/' },
  { id: 'o31', nameBn: 'সমাজ সেবা অধিদপ্তর', nameEn: 'Department of Social Services (DSS)', slug: 'dss', organizationType: 'directorate', ministryCode: 'MOSW', officialUrl: 'https://dss.gov.bd/' },
  { id: 'o32', nameBn: 'মহিলা বিষয়ক অধিদপ্তর', nameEn: 'Department of Women Affairs', slug: 'dwa', organizationType: 'directorate', ministryCode: 'MOWCA', officialUrl: 'https://dwa.gov.bd/' },
  { id: 'o33', nameBn: 'শ্রম অধিদপ্তর', nameEn: 'Department of Labour', slug: 'labour-dept', organizationType: 'directorate', ministryCode: 'MOLE', officialUrl: 'https://labour.gov.bd/' },
  { id: 'o34', nameBn: 'বাংলাদেশ কারিগরি শিক্ষা বোর্ড', nameEn: 'Bangladesh Technical Education Board (BTEB)', slug: 'bteb', organizationType: 'board', ministryCode: 'MOST', officialUrl: 'https://bteb.gov.bd/' },
  { id: 'o35', nameBn: 'অভিবাসী কল্যাণ অধিদপ্তর', nameEn: 'Welfare of Expatriates Welfare Department', slug: 'welfare-expat', organizationType: 'directorate', ministryCode: 'MOEWOE', officialUrl: 'https://welfarebureau.gov.bd/' },
  { id: 'o36', nameBn: 'বাংলাদেশ ক্রীড়া শিক্ষা প্রতিষ্ঠান', nameEn: 'Bangladesh Krira Shiksha Pratisthan (BKSP)', slug: 'bksp', organizationType: 'institute', ministryCode: 'MOYS', officialUrl: 'https://bksp.gov.bd/' },
  { id: 'o37', nameBn: 'বাংলাদেশ পর্যটন কর্পোরেশন', nameEn: 'Bangladesh Parjatan Corporation (BPC)', slug: 'bpc', organizationType: 'corporation', ministryCode: 'MOCAT', officialUrl: 'https://parjatan.gov.bd/' },
  { id: 'o38', nameBn: 'বাংলাদেশ সিভিল এভিয়েশন অথরিটি', nameEn: 'Civil Aviation Authority of Bangladesh (CAAB)', slug: 'caab', organizationType: 'authority', ministryCode: 'MOCAT', officialUrl: 'https://caab.gov.bd/' },
  { id: 'o39', nameBn: 'বাংলাদেশ রেলওয়ে', nameEn: 'Bangladesh Railway', slug: 'bangladesh-railway', organizationType: 'department', ministryCode: 'MOR', officialUrl: 'https://railway.gov.bd/', addressEn: '40, New Airport Road, Dhaka', addressBn: '৪০, নতুন বিমানবন্দর রোড, ঢাকা' },
]

// ─── Services (19) ───
export const services = [
  {
    id: 's1', slug: 'passport',
    titleBn: 'পাসপোর্ট সেবা', titleEn: 'Passport Service',
    descriptionBn: 'বাংলাদেশি নাগরিকদের জন্য আন্তর্জাতিক ভ্রমণের পাসপোর্ট ইস্যু, নবায়ন ও সংশোধন সেবা।',
    descriptionEn: 'Issuance, renewal and correction of international travel passports for Bangladeshi citizens.',
    category: 'passport-immigration', sector: 'Citizen Identity',
    orgSlug: 'immigration-passports',
    serviceUrl: 'https://www.epassport.gov.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: true,
    requiredDocuments: 'জাতীয় পরিচয়পত্র, জন্ম নিবন্ধন সনদ, পূর্ববর্তী পাসপোর্ট (থাকলে), ছবি, ফিসের প্রমাণ||National ID, Birth Certificate, Previous Passport (if any), Photo, Fee payment proof',
    fees: 'সাধারণ: ৪০০০ টাকা, জরুরি: ৬০০০ টাকা, অতি জরুরি: ৮০০০ টাকা||Regular: 4000 BDT, Urgent: 6000 BDT, Super Urgent: 8000 BDT',
    processingTime: 'সাধারণ: ২১ দিন, জরুরি: ৭ দিন, অতি জরুরি: ৩ দিন||Regular: 21 days, Urgent: 7 days, Super Urgent: 3 days',
    eligibility: 'বাংলাদেশি নাগরিক||Bangladeshi citizens',
    sourceUrl: 'https://www.passport.gov.bd/',
  },
  {
    id: 's2', slug: 'birth-registration',
    titleBn: 'জন্ম নিবন্ধন', titleEn: 'Birth Registration',
    descriptionBn: 'নাগরিকদের জন্ম সংক্রান্ত তথ্য সরকারি ডাটাবেসে নিবন্ধন ও সনদ প্রদান।',
    descriptionEn: 'Registration of citizen birth records in the government database and certificate issuance.',
    category: 'citizen-services', sector: 'Citizen Identity',
    orgSlug: 'birth-death-registration',
    serviceUrl: 'https://bdris.gov.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: true,
    requiredDocuments: 'হাসপাতালের সনদ, পিতামাতার জাতীয় পরিচয়পত্র, ঠিকানার প্রমাণ||Hospital certificate, Parents NID, Address proof',
    fees: 'অনলাইন আবেদন: বিনামূল্যে, দ্রুত সেবা: ১০০ টাকা||Online application: Free, Expedited: 100 BDT',
    processingTime: 'সাধারণ: ৪৫ দিন, দ্রুত: ৭ দিন||Regular: 45 days, Expedited: 7 days',
    eligibility: 'সকল বাংলাদেশি নাগরিক||All Bangladeshi citizens',
    sourceUrl: 'https://bdris.gov.bd/',
  },
  {
    id: 's3', slug: 'national-id',
    titleBn: 'জাতীয় পরিচয়পত্র (NID)', titleEn: 'National Identity Card (NID)',
    descriptionBn: 'বাংলাদেশি নাগরিকদের জন্য জাতীয় পরিচয়পত্র ইস্যু, সংশোধন ও নবায়ন সেবা।',
    descriptionEn: 'Issuance, correction and renewal of National ID cards for Bangladeshi citizens.',
    category: 'citizen-services', sector: 'Citizen Identity',
    orgSlug: 'nid-registration',
    serviceUrl: 'https://services.nidw.gov.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: true,
    requiredDocuments: 'জন্ম নিবন্ধন সনদ, ঠিকানার প্রমাণ, পিতামাতার জাতীয় পরিচয়পত্র||Birth Certificate, Address proof, Parents NID',
    fees: 'নতুন: বিনামূল্যে, সংশোধন: ১১৫ টাকা||New: Free, Correction: 115 BDT',
    processingTime: 'নতুন: ৯০ দিন, সংশোধন: ৪৫ দিন||New: 90 days, Correction: 45 days',
    eligibility: '১৮ বছর বা তদূর্ধ্ব বাংলাদেশি নাগরিক||Bangladeshi citizens aged 18 or above',
    sourceUrl: 'https://services.nidw.gov.bd/',
  },
  {
    id: 's4', slug: 'land-registration',
    titleBn: 'ভূমি খতিয়ান ও নামজারি', titleEn: 'Land Record & Mutation (Namjari)',
    descriptionBn: 'ভূমির মালিকানা পরিবর্তন, খতিয়ান সংশোধন ও নতুন খতিয়ান সৃষ্টি সেবা।',
    descriptionEn: 'Land ownership transfer, khatian correction and new khatian creation services.',
    category: 'land', sector: 'Land',
    orgSlug: 'land-records',
    serviceUrl: 'https://www.land.gov.bd/',
    mobileAvailable: false, onlineApplication: false, isPopular: true,
    requiredDocuments: 'দলিল, খতিয়ান, পরিচয়পত্র, ঠিকানার প্রমাণ||Deed, Khatian, ID, Address proof',
    fees: 'মূল্যের উপর ভিত্তি করে নির্ধারিত||Based on property value',
    processingTime: '৯০ থেকে ১৮০ দিন||90 to 180 days',
    eligibility: 'ভূমি মালিক বা ক্রেতা||Land owner or buyer',
    sourceUrl: 'https://www.land.gov.bd/',
  },
  {
    id: 's5', slug: 'vehicle-registration',
    titleBn: 'যানবাহন নিবন্ধন', titleEn: 'Vehicle Registration',
    descriptionBn: 'নতুন যানবাহনের নিবন্ধন, মালিকানা পরিবর্তন ও ফিটনেস সনদ সেবা।',
    descriptionEn: 'New vehicle registration, ownership transfer and fitness certificate services.',
    category: 'transport', sector: 'Transport',
    orgSlug: 'brta',
    serviceUrl: 'https://brta.gov.bd/',
    mobileAvailable: false, onlineApplication: true, isPopular: true,
    requiredDocuments: 'গাড়ির চালান, বীমা, ট্যাক্স পরিশোধের প্রমাণ, পরিচয়পত্র||Invoice, Insurance, Tax payment proof, ID',
    fees: 'যানবাহনের ধরন অনুযায়ী||Based on vehicle type',
    processingTime: '৩০ দিন||30 days',
    eligibility: 'যানবাহন মালিক||Vehicle owners',
    sourceUrl: 'https://brta.gov.bd/',
  },
  {
    id: 's6', slug: 'driving-license',
    titleBn: 'ড্রাইভিং লাইসেন্স', titleEn: 'Driving License',
    descriptionBn: 'নতুন ড্রাইভিং লাইসেন্স, নবায়ন ও সংশোধন সেবা।',
    descriptionEn: 'New driving license, renewal and correction services.',
    category: 'transport', sector: 'Transport',
    orgSlug: 'brta',
    serviceUrl: 'https://brta.gov.bd/',
    mobileAvailable: false, onlineApplication: true, isPopular: true,
    requiredDocuments: 'পরিচয়পত্র, মেডিকেল সনদ, শিক্ষা সনদ, বয়সের প্রমাণ||ID, Medical certificate, Education certificate, Age proof',
    fees: 'প্রশিক্ষণ: ৫০০০ টাকা, লাইসেন্স: ১২৫০ টাকা||Training: 5000 BDT, License: 1250 BDT',
    processingTime: '৯০ দিন||90 days',
    eligibility: '১৮ বছর বা তদূর্ধ্ব||Aged 18 or above',
    sourceUrl: 'https://brta.gov.bd/',
  },
  {
    id: 's7', slug: 'income-tax',
    titleBn: 'আয়কর নিবন্ধন ও দাখিল', titleEn: 'Income Tax Registration & Filing',
    descriptionBn: 'আয়কর শনাক্তকরণ নম্বর (TIN), কর দাখিল ও সনদ সংক্রান্ত সেবা।',
    descriptionEn: 'TIN, tax filing and certificate related services.',
    category: 'tax', sector: 'Tax',
    orgSlug: 'nbr',
    serviceUrl: 'https://secure.etax-rdc.gov.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: true,
    requiredDocuments: 'পরিচয়পত্র, আয়ের প্রমাণ, ব্যাংক হিসাব||ID, Income proof, Bank account',
    fees: 'বিনামূল্যে (TIN নিবন্ধন)||Free (TIN registration)',
    processingTime: 'তাৎক্ষণিক||Instant',
    eligibility: 'আয়কর যোগ্য আয়ের অধিকারী নাগরিক||Citizens with taxable income',
    sourceUrl: 'https://nbr.gov.bd/',
  },
  {
    id: 's8', slug: 'vat-registration',
    titleBn: 'ভ্যাট নিবন্ধন', titleEn: 'VAT Registration',
    descriptionBn: 'ব্যবসা প্রতিষ্ঠানের জন্য ভ্যাট (মূল্য সংযোজন কর) নিবন্ধন সেবা।',
    descriptionEn: 'Value Added Tax registration services for businesses.',
    category: 'tax', sector: 'Tax',
    orgSlug: 'nbr',
    serviceUrl: 'https://vatreg.nbr.gov.bd/',
    mobileAvailable: false, onlineApplication: true, isPopular: false,
    requiredDocuments: 'ব্যবসার লাইসেন্স, ট্রেড লাইসেন্স, ব্যাংক হিসাব||Business license, Trade license, Bank account',
    fees: 'বিনামূল্যে||Free',
    processingTime: '৭ দিন||7 days',
    eligibility: 'বার্ষিক টার্নওভার ৫০ লক্ষ টাকা বা তার বেশি||Annual turnover 50 lakh BDT or more',
    sourceUrl: 'https://nbr.gov.bd/',
  },
  {
    id: 's9', slug: 'trade-license',
    titleBn: 'ট্রেড লাইসেন্স', titleEn: 'Trade License',
    descriptionBn: 'ব্যবসা প্রতিষ্ঠানের জন্য ট্রেড লাইসেন্স ইস্যু ও নবায়ন।',
    descriptionEn: 'Issuance and renewal of trade licenses for businesses.',
    category: 'business', sector: 'Business',
    orgSlug: 'dss',
    serviceUrl: 'https://citizen.services.gov.bd/',
    mobileAvailable: false, onlineApplication: true, isPopular: false,
    requiredDocuments: 'পরিচয়পত্র, ঠিকানার প্রমাণ, ভাড়ার চুক্তি||ID, Address proof, Rental agreement',
    fees: 'সিটি কর্পোরেশন/পৌরসভা অনুযায়ী||Per City Corporation/Municipality',
    processingTime: '৭ দিন||7 days',
    eligibility: 'ব্যবসা মালিক||Business owners',
    sourceUrl: 'https://citizen.services.gov.bd/',
  },
  {
    id: 's10', slug: 'electricity-connection',
    titleBn: 'বিদ্যুৎ সংযোগ', titleEn: 'Electricity Connection',
    descriptionBn: 'নতুন বিদ্যুৎ সংযোগ, লোড বৃদ্ধি ও বিল পরিশোধ সেবা।',
    descriptionEn: 'New electricity connection, load enhancement and bill payment services.',
    category: 'utility', sector: 'Utility',
    orgSlug: 'desco',
    serviceUrl: 'https://www.desco.org.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: false,
    requiredDocuments: 'পরিচয়পত্র, ঠিকানার প্রমাণ, সম্পত্তির দলিল||ID, Address proof, Property deed',
    fees: 'লোড অনুযায়ী||Based on load',
    processingTime: '১৫ থেকে ৩০ দিন||15 to 30 days',
    eligibility: 'সম্পত্তি মালিক বা ভাড়াটে||Property owner or tenant',
    sourceUrl: 'https://www.desco.org.bd/',
  },
  {
    id: 's11', slug: 'exam-results',
    titleBn: 'পরীক্ষার ফলাফল', titleEn: 'Examination Results',
    descriptionBn: 'এসএসসি, এইচএসসি, জেএসসি ও অন্যান্য পাবলিক পরীক্ষার ফলাফল অনলাইনে দেখুন।',
    descriptionEn: 'View SSC, HSC, JSC and other public examination results online.',
    category: 'education', sector: 'Education',
    orgSlug: 'dshe',
    serviceUrl: 'https://eboardresults.com/',
    mobileAvailable: true, onlineApplication: false, isPopular: true,
    requiredDocuments: 'রোল নম্বর, রেজিস্ট্রেশন নম্বর||Roll number, Registration number',
    fees: 'বিনামূল্যে||Free',
    processingTime: 'তাৎক্ষণিক||Instant',
    eligibility: 'পরীক্ষার্থী||Exam candidates',
    sourceUrl: 'https://eboardresults.com/',
  },
  {
    id: 's12', slug: 'social-safety-net',
    titleBn: 'সামাজিক নিরাপত্তা কর্মসূচি', titleEn: 'Social Safety Net Programs',
    descriptionBn: 'বয়স্ক ভাতা, বিধবা ভাতা, প্রতিবন্ধী ভাতা সহ সামাজিক নিরাপত্তা সেবা।',
    descriptionEn: 'Elderly allowance, widow allowance, disability allowance and other social safety services.',
    category: 'social-welfare', sector: 'Social Welfare',
    orgSlug: 'dss',
    serviceUrl: 'https://dss.gov.bd/',
    mobileAvailable: false, onlineApplication: false, isPopular: false,
    requiredDocuments: 'পরিচয়পত্র, আয়ের প্রমাণ, বয়সের প্রমাণ||ID, Income proof, Age proof',
    fees: 'বিনামূল্যে||Free',
    processingTime: 'প্রাসঙ্গিক অফিসে আবেদন প্রক্রিয়াধীন||Application processed at relevant office',
    eligibility: 'যোগ্য নাগরিক||Eligible citizens',
    sourceUrl: 'https://dss.gov.bd/',
  },
  {
    id: 's13', slug: 'railway-ticket',
    titleBn: 'রেলওয়ে টিকিট', titleEn: 'Railway Ticket Booking',
    descriptionBn: 'বাংলাদেশ রেলওয়ের অনলাইন টিকিট বুকিং সেবা।',
    descriptionEn: 'Online ticket booking service of Bangladesh Railway.',
    category: 'transport', sector: 'Transport',
    orgSlug: 'bangladesh-railway',
    serviceUrl: 'https://eticket.railway.gov.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: true,
    requiredDocuments: 'পরিচয়পত্র, মোবাইল নম্বর||ID, Mobile number',
    fees: 'রুট অনুযায়ী||Based on route',
    processingTime: 'তাৎক্ষণিক||Instant',
    eligibility: 'সকল নাগরিক||All citizens',
    sourceUrl: 'https://eticket.railway.gov.bd/',
  },
  {
    id: 's14', slug: 'visa',
    titleBn: 'ভিসা সেবা', titleEn: 'Visa Services',
    descriptionBn: 'বিদেশি নাগরিকদের জন্য বাংলাদেশ ভিসা ইস্যু ও সংশোধন সেবা।',
    descriptionEn: 'Issuance and correction of Bangladesh visa for foreign citizens.',
    category: 'passport-immigration', sector: 'Immigration',
    orgSlug: 'immigration-passports',
    serviceUrl: 'https://www.visa.gov.bd/',
    mobileAvailable: false, onlineApplication: true, isPopular: false,
    requiredDocuments: 'পাসপোর্ট, ছবি, আমন্ত্রণ পত্র, ফিসের প্রমাণ||Passport, Photo, Invitation letter, Fee payment proof',
    fees: 'ভিসার ধরন অনুযায়ী||Based on visa type',
    processingTime: '৭ দিন||7 days',
    eligibility: 'বিদেশি নাগরিক||Foreign citizens',
    sourceUrl: 'https://www.visa.gov.bd/',
  },
  {
    id: 's15', slug: 'health-care',
    titleBn: 'সরকারি হাসপাতাল সেবা', titleEn: 'Government Hospital Services',
    descriptionBn: 'সরকারি হাসপাতালে চিকিৎসা সেবা, বিনামূল্যে ওষুধ ও রোগ নির্ণয়।',
    descriptionEn: 'Medical services, free medicines and diagnostics at government hospitals.',
    category: 'health', sector: 'Health',
    orgSlug: 'dghs',
    serviceUrl: 'https://dghs.gov.bd/',
    mobileAvailable: false, onlineApplication: false, isPopular: true,
    requiredDocuments: 'পরিচয়পত্র, জন্ম নিবন্ধন||ID, Birth certificate',
    fees: 'বিনামূল্যে বা ভর্তি ফি||Free or admission fee',
    processingTime: 'তাৎক্ষণিক||Immediate',
    eligibility: 'সকল নাগরিক||All citizens',
    sourceUrl: 'https://dghs.gov.bd/',
  },
  {
    id: 's16', slug: 'agriculture-extension',
    titleBn: 'কৃষি সম্প্রসারণ সেবা', titleEn: 'Agricultural Extension Services',
    descriptionBn: 'কৃষকদের প্রযুক্তিগত পরামর্শ, বীজ, সার ও কৃষি ঋণ সেবা।',
    descriptionEn: 'Technical advice, seeds, fertilizers and agricultural loan services for farmers.',
    category: 'agriculture', sector: 'Agriculture',
    orgSlug: 'dae',
    serviceUrl: 'https://dae.gov.bd/',
    mobileAvailable: true, onlineApplication: false, isPopular: false,
    requiredDocuments: 'পরিচয়পত্র, জমির দলিল||ID, Land deed',
    fees: 'বিনামূল্যে পরামর্শ||Free consultation',
    processingTime: 'তাৎক্ষণিক||Immediate',
    eligibility: 'কৃষক||Farmers',
    sourceUrl: 'https://dae.gov.bd/',
  },
  {
    id: 's17', slug: 'disaster-relief',
    titleBn: 'দুর্যোগ ত্রাণ সেবা', titleEn: 'Disaster Relief Services',
    descriptionBn: 'দুর্যোগ কবলিত এলাকায় ত্রাণ ও পুনর্বাসন সেবা।',
    descriptionEn: 'Relief and rehabilitation services in disaster-affected areas.',
    category: 'emergency', sector: 'Disaster Management',
    orgSlug: 'ddm',
    serviceUrl: 'https://ddm.gov.bd/',
    mobileAvailable: false, onlineApplication: false, isPopular: false,
    requiredDocuments: 'পরিচয়পত্র, ক্ষতির প্রমাণ||ID, Damage proof',
    fees: 'বিনামূল্যে||Free',
    processingTime: 'দুর্যোগ পরবর্তী মূল্যায়নের ভিত্তিতে||Based on post-disaster assessment',
    eligibility: 'দুর্যোগ কবলিত নাগরিক||Disaster-affected citizens',
    sourceUrl: 'https://ddm.gov.bd/',
  },
  {
    id: 's18', slug: 'overseas-employment',
    titleBn: 'বৈদেশিক কর্মসংস্থান', titleEn: 'Overseas Employment Clearance',
    descriptionBn: 'বিদেশে কর্মসংস্থানের জন্য স্মার্ট কার্ড ও ক্লিয়ারেন্স সেবা।',
    descriptionEn: 'Smart card and clearance services for overseas employment.',
    category: 'employment', sector: 'Employment',
    orgSlug: 'welfare-expat',
    serviceUrl: 'https://www.probashi.gov.bd/',
    mobileAvailable: true, onlineApplication: true, isPopular: false,
    requiredDocuments: 'পাসপোর্ট, ভিসা, চুক্তিপত্র, পরিচয়পত্র||Passport, Visa, Contract, ID',
    fees: '৪০০০ টাকা||4000 BDT',
    processingTime: '৭ দিন||7 days',
    eligibility: 'বিদেশগামী কর্মী||Overseas workers',
    sourceUrl: 'https://www.probashi.gov.bd/',
  },
  {
    id: 's19', slug: 'right-to-information',
    titleBn: 'তথ্য অধিকার আইন', titleEn: 'Right to Information (RTI)',
    descriptionBn: 'তথ্য অধিকার আইন ২০০৯ অনুযায়ী সরকারি তথ্য চাওয়ার সেবা।',
    descriptionEn: 'Service to request government information under Right to Information Act 2009.',
    category: 'information', sector: 'Information',
    orgSlug: 'do-info',
    serviceUrl: 'https://ictd.gov.bd/',
    mobileAvailable: false, onlineApplication: true, isPopular: false,
    requiredDocuments: 'পরিচয়পত্র, আবেদন ফি ১০ টাকা||ID, Application fee 10 BDT',
    fees: '১০ টাকা||10 BDT',
    processingTime: '৩০ দিন||30 days',
    eligibility: 'সকল নাগরিক||All citizens',
    sourceUrl: 'https://ictd.gov.bd/',
  },
]

// ─── Emergency Services (15) ───
export const emergencies = [
  { id: 'e1', nameBn: 'জাতীয় জরুরি সেবা', nameEn: 'National Emergency Service', number: '999', descriptionBn: 'পুলিশ, ফায়ার সার্ভিস ও অ্যাম্বুলেন্স - এক নম্বরে', descriptionEn: 'Police, Fire Service and Ambulance — one number', organization: 'Government of Bangladesh', available247: true, category: 'general' },
  { id: 'e2', nameBn: 'জাতীয় হেল্পলাইন কল সেন্টার', nameEn: 'National Helpline Call Centre', number: '333', descriptionBn: 'সরকারি তথ্য ও সেবা সম্পর্কিত হেল্পলাইন', descriptionEn: 'Helpline for government information and services', organization: 'a2i', available247: true, category: 'information' },
  { id: 'e3', nameBn: 'নারী ও শিশু নির্যাতন প্রতিরোধ হেল্পলাইন', nameEn: 'Women & Child Repression Helpline', number: '109', descriptionBn: 'নারী ও শিশু নির্যাতন সংক্রান্ত অভিযোগ', descriptionEn: 'Reports of women and child abuse', organization: 'Ministry of Women and Children Affairs', available247: true, category: 'women-children' },
  { id: 'e4', nameBn: 'দুর্নীতি দমন কমিশন হটলাইন', nameEn: 'Anti-Corruption Hotline', number: '106', descriptionBn: 'দুর্নীতির অভিযোগ দাখিল', descriptionEn: 'Lodge corruption complaints', organization: 'Anti-Corruption Commission', available247: true, category: 'general' },
  { id: 'e5', nameBn: 'অগ্নিনির্বাপন সেবা', nameEn: 'Fire Service', number: '199', descriptionBn: 'অগ্নিকাণ্ড ও উদ্ধার কাজে', descriptionEn: 'For fires and rescue operations', organization: 'Bangladesh Fire Service', available247: true, category: 'fire' },
  { id: 'e6', nameBn: 'পুলিশ সাহায্যকেন্দ্র', nameEn: 'Police Helpline', number: '100', descriptionBn: 'পুলিশ সাহায্য ও অভিযোগ', descriptionEn: 'Police assistance and complaints', organization: 'Bangladesh Police', available247: true, category: 'police' },
  { id: 'e7', nameBn: 'সড়ক দুর্ঘটনা', nameEn: 'Road Accident Hotline', number: '9666060', descriptionBn: 'সড়ক দুর্ঘটনা সংক্রান্ত তথ্য', descriptionEn: 'Road accident information', organization: 'BRTA', available247: true, category: 'transport' },
  { id: 'e8', nameBn: 'বিদ্যুৎ সংক্রান্ত জরুরি', nameEn: 'Electricity Emergency', number: '16216', descriptionBn: 'DESCO বিদ্যুৎ সংক্রান্ত জরুরি', descriptionEn: 'DESCO electricity emergencies', organization: 'DESCO', available247: true, category: 'utility' },
  { id: 'e9', nameBn: 'পানি সরবরাহ জরুরি', nameEn: 'Water Supply Emergency', number: '16458', descriptionBn: 'পানি সরবরাহ সংক্রান্ত জরুরি', descriptionEn: 'Water supply emergencies', organization: 'WASA', available247: true, category: 'utility' },
  { id: 'e10', nameBn: 'শিশু হেল্পলাইন', nameEn: 'Child Helpline', number: '1098', descriptionBn: 'শিশুদের সাহায্য ও সুরক্ষা', descriptionEn: 'Child help and protection', organization: 'Ministry of Women and Children Affairs', available247: true, category: 'children' },
  { id: 'e11', nameBn: 'সুইসাইড প্রতিরোধ হেল্পলাইন', nameEn: 'Suicide Prevention Helpline', number: '16435', descriptionBn: 'মানসিক সহায়তা ও পরামর্শ', descriptionEn: 'Mental support and counseling', organization: 'Aparajeyo Bangladesh', available247: true, category: 'health' },
  { id: 'e12', nameBn: 'প্রবাসী কল্যাণ হেল্পলাইন', nameEn: 'Expatriate Welfare Helpline', number: '16355', descriptionBn: 'প্রবাসী কর্মীদের সাহায্য', descriptionEn: 'Help for expatriate workers', organization: 'Ministry of Expatriates Welfare', available247: true, category: 'expatriate' },
  { id: 'e13', nameBn: 'কৃষি কল সেন্টার', nameEn: 'Agriculture Call Centre', number: '16123', descriptionBn: 'কৃষি সম্পর্কিত পরামর্শ', descriptionEn: 'Agricultural advice', organization: 'Ministry of Agriculture', available247: false, category: 'agriculture' },
  { id: 'e14', nameBn: 'স্বাস্থ্য বাতাস', nameEn: 'Health Batas', number: '16263', descriptionBn: 'স্বাস্থ্য সেবা ও পরামর্শ', descriptionEn: 'Health service and advice', organization: 'DGHS', available247: true, category: 'health' },
  { id: 'e15', nameBn: 'সাইবার ক্রাইম হেল্পলাইন', nameEn: 'Cyber Crime Helpline', number: '16318', descriptionBn: 'সাইবার অপরাধ সংক্রান্ত অভিযোগ', descriptionEn: 'Cyber crime complaints', organization: 'Cyber Crime Unit, Police', available247: true, category: 'cyber' },
]

// ─── Notices (6) ───
export const notices = [
  { id: 'n1', titleBn: 'এসএসসি পরীক্ষার ফলাফল প্রকাশ', titleEn: 'SSC Examination Results Published', organization: 'Education Boards Bangladesh', category: 'public-exam', publishedAt: '2025-05-12', excerptBn: 'এসএসসি ও সমমান পরীক্ষার ফলাফল প্রকাশ করা হয়েছে।', excerptEn: 'SSC and equivalent examination results have been published.', sourceUrl: 'https://eboardresults.com/' },
  { id: 'n2', titleBn: 'জাতীয় পরিচয়পত্র বিতরণ কার্যক্রম', titleEn: 'NID Distribution Programme', organization: 'NID Wing', category: 'service-notice', publishedAt: '2025-09-15', excerptBn: 'নতুন জাতীয় পরিচয়পত্র বিতরণ শুরু হয়েছে।', excerptEn: 'Distribution of new National ID cards has started.', sourceUrl: 'https://services.nidw.gov.bd/' },
  { id: 'n3', titleBn: 'পাসপোর্ট ফি সংশোধন', titleEn: 'Passport Fee Revision Notice', organization: 'Department of Immigration & Passports', category: 'circular', publishedAt: '2025-08-22', excerptBn: 'ই-পাসপোর্ট ফি সংশোধন প্রজ্ঞাপন প্রকাশিত।', excerptEn: 'Revised e-passport fee notification published.', sourceUrl: 'https://www.passport.gov.bd/' },
  { id: 'n4', titleBn: 'বার্ষিক কর দাখিলের শেষ তারিখ', titleEn: 'Annual Tax Filing Deadline', organization: 'NBR', category: 'tax-notice', publishedAt: '2025-10-01', deadline: '2025-11-30', excerptBn: 'ব্যক্তিগত আয়কর দাখিলের শেষ তারিখ ৩০ নভেম্বর।', excerptEn: 'Personal income tax filing deadline is November 30.', sourceUrl: 'https://nbr.gov.bd/' },
  { id: 'n5', titleBn: 'চট্টগ্রাম বন্দরে জাহাজ চলাচল বিজ্ঞপ্তি', titleEn: 'Chattogram Port Vessel Movement Notice', organization: 'Chattogram Port Authority', category: 'notice', publishedAt: '2025-10-02', excerptBn: 'চট্টগ্রাম বন্দরে জাহাজ চলাচলের তফসিল প্রকাশিত।', excerptEn: 'Vessel movement schedule at Chattogram Port published.', sourceUrl: 'https://cpa.gov.bd/' },
  { id: 'n6', titleBn: 'ভর্তি কার্যক্রম বিজ্ঞপ্তি', titleEn: 'University Admission Circular', organization: 'UGC', category: 'admission', publishedAt: '2025-09-25', deadline: '2025-10-20', excerptBn: 'পাবলিক বিশ্ববিদ্যালয় ভর্তি বিজ্ঞপ্তি প্রকাশিত।', excerptEn: 'Public university admission circular published.', sourceUrl: 'https://www.ugc.gov.bd/' },
]

// ─── Recruitments (5) ───
export const recruitments = [
  { id: 'r1', titleBn: 'সহকারী পরিচালক পদে নিয়োগ বিজ্ঞপ্তি', titleEn: 'Recruitment for Assistant Director Position', organization: 'Bangladesh Bank', positionBn: 'সহকারী পরিচালক', positionEn: 'Assistant Director', publishedAt: '2025-09-20', deadline: '2025-10-25', applicationUrl: 'https://erecruitment.bb.org.bd/', sourceUrl: 'https://erecruitment.bb.org.bd/' },
  { id: 'r2', titleBn: 'প্রশাসনিক কর্মকর্তা নিয়োগ', titleEn: 'Administrative Officer Recruitment', organization: 'Ministry of Public Administration', positionBn: 'প্রশাসনিক কর্মকর্তা', positionEn: 'Administrative Officer', publishedAt: '2025-09-15', deadline: '2025-10-30', applicationUrl: 'https://bpsc.gov.bd/', sourceUrl: 'https://bpsc.gov.bd/' },
  { id: 'r3', titleBn: 'প্রাথমিক বিদ্যালয় শিক্ষক নিয়োগ', titleEn: 'Primary School Teacher Recruitment', organization: 'Directorate of Primary Education', positionBn: 'সহকারী শিক্ষক', positionEn: 'Assistant Teacher', publishedAt: '2025-10-01', deadline: '2025-11-15', applicationUrl: 'https://dpe.teletalk.com.bd/', sourceUrl: 'https://dpe.gov.bd/' },
  { id: 'r4', titleBn: 'বিআরটিএ মোটর চালক নিয়োগ', titleEn: 'BRTA Motor Vehicle Inspector', organization: 'BRTA', positionBn: 'মোটর যান পরিদর্শক', positionEn: 'Motor Vehicle Inspector', publishedAt: '2025-09-10', deadline: '2025-10-15', applicationUrl: 'https://brta.gov.bd/', sourceUrl: 'https://brta.gov.bd/' },
  { id: 'r5', titleBn: 'নির্বাচন কমিশন ফিল্ড সহকারী নিয়োগ', titleEn: 'Election Commission Field Assistant', organization: 'Election Commission', positionBn: 'ফিল্ড সহকারী', positionEn: 'Field Assistant', publishedAt: '2025-09-28', deadline: '2025-10-28', applicationUrl: 'https://ec.org.bd/', sourceUrl: 'https://ec.org.bd/' },
]

// ─── Forms (12) ───
export const forms = [
  { id: 'f1', titleBn: 'পাসপোর্ট আবেদন ফরম', titleEn: 'Passport Application Form', category: 'passport', organization: 'Department of Immigration & Passports', officialUrl: 'https://www.passport.gov.bd/', sourceUrl: 'https://www.passport.gov.bd/' },
  { id: 'f2', titleBn: 'জন্ম নিবন্ধন আবেদন ফরম', titleEn: 'Birth Registration Application Form', category: 'citizen', organization: 'Office of the Registrar General, Birth & Death Registration', officialUrl: 'https://bdris.gov.bd/', sourceUrl: 'https://bdris.gov.bd/' },
  { id: 'f3', titleBn: 'ট্রেড লাইসেন্স আবেদন ফরম', titleEn: 'Trade License Application Form', category: 'business', organization: 'City Corporation', officialUrl: 'https://citizen.services.gov.bd/', sourceUrl: 'https://citizen.services.gov.bd/' },
  { id: 'f4', titleBn: 'আয়কর রিটার্ন ফরম', titleEn: 'Income Tax Return Form', category: 'tax', organization: 'NBR', officialUrl: 'https://nbr.gov.bd/', sourceUrl: 'https://nbr.gov.bd/' },
  { id: 'f5', titleBn: 'ভূমি খতিয়ান আবেদন', titleEn: 'Land Khatian Application', category: 'land', organization: 'Directorate of Land Record and Survey', officialUrl: 'https://www.land.gov.bd/', sourceUrl: 'https://www.land.gov.bd/' },
  { id: 'f6', titleBn: 'টিআইন আবেদন ফরম', titleEn: 'TIN Application Form', category: 'tax', organization: 'NBR', officialUrl: 'https://secure.etax-rdc.gov.bd/', sourceUrl: 'https://nbr.gov.bd/' },
  { id: 'f7', titleBn: 'ড্রাইভিং লাইসেন্স আবেদন', titleEn: 'Driving License Application', category: 'transport', organization: 'BRTA', officialUrl: 'https://brta.gov.bd/', sourceUrl: 'https://brta.gov.bd/' },
  { id: 'f8', titleBn: 'যানবাহন নিবন্ধন ফরম', titleEn: 'Vehicle Registration Form', category: 'transport', organization: 'BRTA', officialUrl: 'https://brta.gov.bd/', sourceUrl: 'https://brta.gov.bd/' },
  { id: 'f9', titleBn: 'অনলাইন ভিসা আবেদন', titleEn: 'Online Visa Application', category: 'passport', organization: 'Department of Immigration & Passports', officialUrl: 'https://www.visa.gov.bd/', sourceUrl: 'https://www.visa.gov.bd/' },
  { id: 'f10', titleBn: 'নতুন বিদ্যুৎ সংযোগ আবেদন', titleEn: 'New Electricity Connection Application', category: 'utility', organization: 'DESCO', officialUrl: 'https://www.desco.org.bd/', sourceUrl: 'https://www.desco.org.bd/' },
  { id: 'f11', titleBn: 'বিয়ের নিবন্ধন ফরম', titleEn: 'Marriage Registration Form', category: 'citizen', organization: 'Local Government', officialUrl: 'https://bdris.gov.bd/', sourceUrl: 'https://bdris.gov.bd/' },
  { id: 'f12', titleBn: 'সামাজিক নিরাপত্তা ভাতা আবেদন', titleEn: 'Social Safety Net Allowance Application', category: 'welfare', organization: 'Department of Social Services', officialUrl: 'https://dss.gov.bd/', sourceUrl: 'https://dss.gov.bd/' },
]

// ─── Government Links (14) ───
export const govLinks = [
  { id: 'l1', titleBn: 'বাংলাদেশ সরকারের জাতীয় পোর্টাল', titleEn: 'Bangladesh National Portal', organization: 'Government of Bangladesh', category: 'national', url: 'https://bangladesh.gov.bd/' },
  { id: 'l2', titleBn: 'প্রধানমন্ত্রীর কার্যালয়', titleEn: "Prime Minister's Office", organization: 'Government of Bangladesh', category: 'office', url: 'https://pmo.gov.bd/' },
  { id: 'l3', titleBn: 'মন্ত্রিপরিষদ বিভাগ', titleEn: 'Cabinet Division', organization: 'Government of Bangladesh', category: 'office', url: 'https://cabinet.gov.bd/' },
  { id: 'l4', titleBn: 'জনপ্রশাসন মন্ত্রণালয়', titleEn: 'Ministry of Public Administration', organization: 'MOPA', category: 'ministry', url: 'https://mopa.gov.bd/' },
  { id: 'l5', titleBn: 'আয়কর বোর্ড', titleEn: 'National Board of Revenue', organization: 'NBR', category: 'tax', url: 'https://nbr.gov.bd/' },
  { id: 'l6', titleBn: 'বাংলাদেশ ব্যাংক', titleEn: 'Bangladesh Bank', organization: 'Bangladesh Bank', category: 'finance', url: 'https://www.bangladesh-bank.org/' },
  { id: 'l7', titleBn: 'নির্বাচন কমিশন', titleEn: 'Election Commission', organization: 'EC', category: 'commission', url: 'https://ec.org.bd/' },
  { id: 'l8', titleBn: 'অর্থ মন্ত্রণালয়', titleEn: 'Ministry of Finance', organization: 'MOF', category: 'ministry', url: 'https://mof.gov.bd/' },
  { id: 'l9', titleBn: 'বিজ্ঞান ও প্রযুক্তি মন্ত্রণালয়', titleEn: 'Ministry of Science & Technology', organization: 'MOST', category: 'ministry', url: 'https://most.gov.bd/' },
  { id: 'l10', titleBn: 'স্বাস্থ্য অধিদপ্তর', titleEn: 'Directorate General of Health Services', organization: 'DGHS', category: 'directorate', url: 'https://dghs.gov.bd/' },
  { id: 'l11', titleBn: 'মাধ্যমিক ও উচ্চ শিক্ষা অধিদপ্তর', titleEn: 'Directorate of Secondary and Higher Education', organization: 'DSHE', category: 'directorate', url: 'https://dshe.gov.bd/' },
  { id: 'l12', titleBn: 'পরিসংখ্যান ব্যুরো', titleEn: 'Bangladesh Bureau of Statistics', organization: 'BBS', category: 'bureau', url: 'https://bbs.gov.bd/' },
  { id: 'l13', titleBn: 'স্থানীয় সরকার প্রকৌশল অধিদপ্তর', titleEn: 'Local Government Engineering Department', organization: 'LGED', category: 'directorate', url: 'https://lged.gov.bd/' },
  { id: 'l14', titleBn: 'জনস্বাস্থ্য প্রকৌশল অধিদপ্তর', titleEn: 'Department of Public Health Engineering', organization: 'DPHE', category: 'directorate', url: 'https://dphe.gov.bd/' },
]
